Initial image import

diff --git a/1.8/test/run b/1.8/test/run
--- a/1.8/test/run
+++ b/1.8/test/run
@@ -1,131 +1,172 @@
 #!/bin/bash
 #
-# The 'run' script performs simple tests that verifies usability
-# of tools, packaged in toolchain image.
+# The 'run' performs a simple test that verifies that S2I image.
+# The main focus here is to excersise the S2I scripts.
 #
 # IMAGE_NAME specifies a name of the candidate image used for testing.
 # The image has to be available before this script is executed.
 #
-# DEBUG environment variable, if not empty, makes 'run' to log every step
-# of testing.
-#
+export IMAGE_NAME=${IMAGE_NAME:-sclorg/python-36-centos7-candidate}
 
-if [ "$DEBUG" != "" ]; then
-  set -x
-fi
+declare -a TEST_APPS=({simple,import-with-vendor,import-without-vendor}-app)
 
-IMAGE_NAME=${IMAGE_NAME:-rhscl-tech-preview/go-toolset-7-rhel7}
-THISDIR=$(dirname ${BASH_SOURCE[0]})
+# TODO: Make command compatible for Mac users
+test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
+image_dir=$(readlink -zf ${test_dir}/..)
 
-function info () {
-    echo -e "\e[1m[INFO] $@\e[0m"
+info() {
+  echo -e "\n\e[1m[INFO] $@\e[0m\n"
 }
 
-function pass () {
-    echo -e "\e[1;32m[PASS] $@\e[0m"
+image_exists() {
+  docker inspect $1 &>/dev/null
 }
 
-function error () {
-    echo -e "\e[1;31m[ERROR] $@\e[0m"
+container_exists() {
+  image_exists $(cat $cid_file)
 }
 
-function check_result() {
-    local label="$1"
-    local result="$2"
-    local expected="$3"
+container_ip() {
+  docker inspect --format="{{ .NetworkSettings.IPAddress }}" $(cat $cid_file)
+}
 
-    if [[ "$result" = "$expected" ]]; then
-        pass "$label: PASS"
-    else
-        error "$label: FAIL ($result)"
-        RESULT=1
+run_s2i_build() {
+  info "Building the ${1} application image ..."
+  pushd ${test_dir}/${1} >/dev/null
+  ./s2i-build
+  popd
+}
+
+prepare() {
+  if ! image_exists ${IMAGE_NAME}; then
+    echo "ERROR: The image ${IMAGE_NAME} must exist before this script is executed."
+    exit 1
+  fi
+  # TODO: S2I build require the application is a valid 'GIT' repository, we
+  # should remove this restriction in the future when a file:// is used.
+  info "Preparing to test ${1} ..."
+  pushd ${test_dir}/${1}/app >/dev/null
+  git init
+  git config user.email "build@localhost" && git config user.name "builder"
+  git add -A && git commit -m "Sample commit"
+  popd >/dev/null
+}
+
+run_test_application() {
+  docker run -t --user=100001 ${CONTAINER_ARGS} --rm --cidfile=${cid_file} ${IMAGE_NAME}-testapp
+}
+
+cleanup_app() {
+  info "Cleaning up app container ..."
+  if [ -f $cid_file ]; then
+    if container_exists; then
+      docker stop $(cat $cid_file)
     fi
+  fi
 }
 
-function test_docker_run_usage () {
+cleanup() {
+  info "Cleaning up the test application image"
+  if image_exists ${IMAGE_NAME}-testapp; then
+    docker rmi -f ${IMAGE_NAME}-testapp
+  fi
+  rm -rf ${test_dir}/${1}/.git
+}
+
+check_result() {
+  local result="$1"
+  if [[ "$result" != "0" ]]; then
+    info "TEST FAILED (${result})"
+    cleanup
+    exit $result
+  fi
+}
+
+wait_for_cid() {
+  local max_attempts=10
+  local sleep_time=1
+  local attempt=1
+  local result=1
+  info "Waiting for application container to start $CONTAINER_ARGS ..."
+  while [ $attempt -le $max_attempts ]; do
+    [ -f $cid_file ] && [ -s $cid_file ] && break
+    attempt=$(( $attempt + 1 ))
+    sleep $sleep_time
+  done
+}
+
+test_s2i_usage() {
+  info "Testing 's2i usage' ..."
+  s2i usage ${s2i_args} ${IMAGE_NAME} &>/dev/null
+}
+
+test_docker_run_usage() {
   info "Testing 'docker run' usage ..."
-
-  docker run --rm $IMAGE_NAME > $TMPDIR/actual-usage
-  check_result "Exit code is zero" $? 0
-
-  diff "$THISDIR"/expected-usage $TMPDIR/actual-usage &> /dev/null
-  check_result "Usage info matches the expected text" $? 0
+  docker run ${IMAGE_NAME} &>/dev/null
 }
 
-function test_sanity_go_usage () {
-  info "Testing 'go -v' usage ..."
+test_scl_usage() {
+  local run_cmd="$1"
+  local expected="$2"
+  local cid_file="$3"
 
-  docker run --rm $IMAGE_NAME go version &> $TMPDIR/actual-go-version
-  check_result "Exit code is zero" $? 0
-
-  grep 'go version go1.8\.3 linux/amd64' $TMPDIR/actual-go-version &> /dev/null
-  check_result "Output contains go version" $? 0
+  info "Testing the image SCL enable"
+  out=$(docker run -t --rm ${IMAGE_NAME} /bin/bash -c "${run_cmd}" 2>&1)
+  if ! echo "${out}" | grep -q "${expected}"; then
+    echo "ERROR[/bin/bash -c "${run_cmd}"] Expected '${expected}', got '${out}'"
+    return 1
+  fi
+  out=$(docker exec $(cat ${cid_file}) /bin/bash -c "${run_cmd}" 2>&1)
+  if ! echo "${out}" | grep -q "${expected}"; then
+    echo "ERROR[exec /bin/bash -c "${run_cmd}"] Expected '${expected}', got '${out}'"
+    return 1
+  fi
+  out=$(docker exec $(cat ${cid_file}) /bin/sh -ic "${run_cmd}" 2>&1)
+  if ! echo "${out}" | grep -q "${expected}"; then
+    echo "ERROR[exec /bin/sh -ic "${run_cmd}"] Expected '${expected}', got '${out}'"
+    return 1
+  fi
 }
 
-function test_go_run () {
-  info "Testing running go program via 'docker run go run foo.go ..."
+test_application() {
+  local cid_file=$(mktemp -u --suffix=.cid)
+  # Verify that the HTTP connection can be established to test application container
+  run_test_application &
 
-  rm -f $TMPDIR/foo $TMPDIR/foo.go
+  # Wait for the container to write it's CID file
+  wait_for_cid
 
-  cat << EOF > $TMPDIR/foo.go
-package main
-
-import "fmt"
-
-func main() {
-    fmt.Println("Hello world from containerized go!")
-}
-EOF
-
-  docker run --rm -v $TMPDIR:$TMPDIR:z $IMAGE_NAME go run $TMPDIR/foo.go &> $TMPDIR/actual-output
-  check_result "Exit code is zero" $? 0
-
-  grep "Hello world from containerized go!" $TMPDIR/actual-output &> /dev/null
-  check_result "Running source works" $? 0
+  test_scl_usage "go version" "go version go1.8" "${cid_file}"
+  check_result $?
+  cleanup_app
 }
 
-function test_go_build () {
-  info "Testing building go program via 'docker run go build foo.go ..."
 
-  rm -f $TMPDIR/foo $TMPDIR/foo.go
+# Since we built the candidate image locally, we don't want S2I attempt to pull
+# it from Docker hub
+export s2i_args="--force-pull=false"
 
-  cat << EOF > $TMPDIR/foo.go
-package main
+# Verify the 'usage' script is working properly when running the base image with 's2i usage ...'
+test_s2i_usage
+check_result $?
 
-import "fmt"
-
-func main() {
-    fmt.Println("Hello world from containerized go!")
-}
-EOF
-
-  docker run --rm -v $TMPDIR:$TMPDIR:z $IMAGE_NAME go build -o $TMPDIR/foo $TMPDIR/foo.go &> /dev/null
-  check_result "Exit code is zero" $? 0
-
-  test -e $TMPDIR/foo
-  check_result "Compiled binary exists" $? 0
-
-  $TMPDIR/foo &> $TMPDIR/actual-output
-
-  grep "Hello world from containerized go!" $TMPDIR/actual-output &> /dev/null
-  check_result "Running binary works" $? 0
-}
-
-TMPDIR=`mktemp -d`
-chmod a+rwx $TMPDIR
-
-RESULT=0
-
+# Verify the 'usage' script is working properly when running the base image with 'docker run ...'
 test_docker_run_usage
-test_sanity_go_usage
-test_go_run
-test_go_build
+check_result $?
 
-rm -rf $TMPDIR
+for app in ${TEST_APPS[@]}; do
+  prepare ${app}
+  run_s2i_build ${app}
+  check_result $?
 
-if [ "$RESULT" = "0" ]; then
-    info "All tests finished"
-else
-    error "Some tests failed"
-    exit $RESULT
-fi
+  # test application with default user
+  test_application
+
+  # test application with random user
+  CONTAINER_ARGS="-u 12345" test_application
+
+  info "All tests for the ${app} finished successfully."
+  cleanup ${app}
+done
+
+info "All tests finished successfully."
